replicaCount: 2

image:
  repository: 731330499337.dkr.ecr.ap-south-1.amazonaws.com/eks-node-app
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

containerPort: 3000

nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
