replicaCount: 0

image:
  repository: 731330499337.dkr.ecr.ap-south-1.amazonaws.com/eks-node-app
  tag: "ff2041f7d24f4c687a23fe1da4709b7475f8347b"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

containerPort: 3000

nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
