replicaCount: 0

image:
  repository: 731330499337.dkr.ecr.ap-south-1.amazonaws.com/eks-node-app
  tag: "70e017de468ee13992a1e7289d8adb4cf77e28aa"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

containerPort: 3000

nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
