apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-node-app
spec:
  replicas: 2

  selector:
    matchLabels:
      app: eks-node-app

  template:
    metadata:
      labels:
        app: eks-node-app

    spec:
      containers:
      - name: eks-node-app
        image: 731330499337.dkr.ecr.ap-south-1.amazonaws.com/eks-node-app:latest
        ports:
        - containerPort: 3000